#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/bash
#lint before pushing to main or staging branch branch
BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|staging)" 

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
npm run lint-server
fi
